// <auto-generated />
namespace Chirper_5._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subscr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subscr));
        
        string IMigrationMetadata.Id
        {
            get { return "201602281649125_subscr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
